### PR TITLE
IDVA3-1642 refactored indivdual statement

### PR DESCRIPTION
**Pull request by JasSmith-ch**
- refactored individual statement

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by eedwards0** [comment]
Try merging in main, as there is a small change which is causing a test to fail.

**Review by eedwards0 — CHANGES_REQUESTED** [review]
Please merge in main to get latest changes

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by eedwards0 — APPROVED** [review]
All tests passing and looks good in Docker

**Pull request merged**
