### PR TITLE
Removal of redundant views and associated routers from web

### PR DESCRIPTION
**Pull request by AlisonGriffiths**
RLE functionality is no longer required. This PR starts the removal the redundant views, routers and handlers.
Left the RLE list screen so as to not break the existing journey.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by PhilipGlover** [comment]
I'm not sure I understand why removing the RLE list screen will break the journey.. I haven't run this but surely we shouldn't select RLE from the PSC type screen?

**Comment by AlisonGriffiths** [comment]
> I'm not sure I understand why removing the RLE list screen will break the journey.. I haven't run this but surely we shouldn't select RLE from the PSC type screen?

This is a quick change I have made the simplest of changes that don't break anything. I don't want to spend too long on it. I was coming it at more from the perspective of sonar and seemed like a quick fix to remove all the screens that we don't have wired up and then our code coverage will improve hopefully.

**Comment by PhilipGlover** [comment]
ok fair enough.

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by PhilipGlover — APPROVED** [review]
-  have run and completed Individual journey
- now I see that removing the RLE_LIST screen would affect `pscTypeHandler.selectPscType` so best to leave that until we remove the PSC Type screen all together
- see Sonar report 100% coverage with this PR

**Pull request merged**
