### PR TITLE
Fix PscType integration test

### PR DESCRIPTION
**Pull request by hepsimo**
PscTypeHandler:
- remove companyNumber from PscType URL (not used in practice)

PscType Int Test:
- import middleware mocks separately, not simple definitions from "allMiddleware.mock"
- stub PscVerificationService.getPscVerification() called by fetchVerification middleware rather than stub the latter directly (more difficult).
- move mockResolvedValueOnce() to beforeEach() in describe block -- seems to fix jest not applying stubbing correctly and tests calling real implementation then timing out
- add back-link content check
- improve describe/it text clarity

Other changes:
- disable coverage in 'npm test' script to simplify debugging
- change jest.runMode to "on-save"
- rename int test to reflect it's for Router/Handler integration

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by eedwards0 — APPROVED** [review]
All looks good

**Pull request merged**
