### PR TITLE
IDVA3-577 Complete functionality for the confirmation screen

### PR DESCRIPTION
**Pull request by AlisonGriffiths**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hepsimo — CHANGES_REQUESTED** [review]
Unit test coverage is great, could you add an integration test for the HTML as well? See individualStatementHander.int.ts in PR #88 for example

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by hepsimo — APPROVED** [review]
Changes look good

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
