### PR TITLE
Add static content to Personal Code view IDVA3-1036

### PR DESCRIPTION
**Pull request by hepsimo**
- add static page content using localisation
- use static placeholder for dynamic text '[Selected PSC]'
- refactor Skeleton Four as Personal Code
- rename files accordingly
- alter previous view's Continue button target

Resolves:
IDVA3-1036

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by PhilipGlover — APPROVED** [review]
- all looks good to me
- english / welsh
- navigation all as expected

Screenshot 2024-03-07 at 1 43 15 pm

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
