### PR TITLE
Feature: Add validation for PSC Type screen

### PR DESCRIPTION
**Pull request by mwejuli-ch**
- Adds validation for PSC Type screen
- Includes plumbing work for future screen/form validation
- Does not include unit tests for new code due to time constraints - to be addressed separately
- Additional comments welcome

### CODE REVIEW

**Comment by mwejuli-ch** [comment]
Re-opening PR

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by PhilipGlover — APPROVED** [review]
- I have successfully run this code
  - seen error message
  - can still proceed if valid data
- needs language localisation, but that will be later work

**Pull request merged**
