### PR TITLE
Add launch config and inspect to nodemon config

### PR DESCRIPTION
**Pull request by PhilipGlover**
see also https://github.com/companieshouse/docker-chs-development/pull/963

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by clewis1 — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by clewis1 — APPROVED** [review]

**Pull request merged**
