### PR TITLE
IDVA3-1304 Get psc-verification filing data from the API

### PR DESCRIPTION
**Pull request by hepsimo**
Add ability to make GET requests for specific psc verification filings so the appropriate info can be displayed on screen

- add getPscVerification to pscVerificationService to make API requests
- add path param function to the PSC Type router that retrieves specific filing data by ID when resolving the submission ID in the URL
- store that data in the user's page request to keep it distinct from any other user requests
- use the submission data to render the appropriate radio button as checked, if indicated
  - :warning: current data model does not have a 'psc-type' property, so have to determine from presence of 'psc-appoinment-id' and 'relevant-officer'. Confirmation needed on this in the low level design
- minor refactorings

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by PhilipGlover — APPROVED** [review]
- have successfully run code
- see the PSC type selected when coming back from both PSC list screens
- in debug I see the data coming from `getPscVerification`
- all tests passed
- all looks good

**Pull request merged**
